CREATE TYPE tipo_empresa AS ENUM ('Pública', 'Privada');

CREATE TABLE tb_empresas (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    razao_social VARCHAR(255) NOT NULL,
    cnpj VARCHAR(20) NOT NULL UNIQUE,
    inscricao_estadual VARCHAR(100) NOT NULL UNIQUE,
    telefone VARCHAR(20),
    email VARCHAR(255) UNIQUE,
    ramo_atividade VARCHAR(255),
    tipo tipo_empresa NOT NULL,
    id_endereco bigint,
    id_usuario bigint,
    CONSTRAINT fk_id_endereco FOREIGN KEY(id_endereco) REFERENCES tb_enderecos(id),
    CONSTRAINT fk_id_usuario FOREIGN KEY(id_usuario) REFERENCES tb_usuarios(id)
);
